#!/bin/bash

function start {
  ./start.sh
}

function stop {
  ./stop.sh
}

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  *)
    echo "Usage: $0 {start|stop}"
    exit 1
esac

exit 0
